// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/glucojack-dark/DarkCockpit.tsx": () => import("../components/mockups/glucojack-dark/DarkCockpit.tsx"),
  "./components/mockups/glucojack-light/LightPremium.tsx": () => import("../components/mockups/glucojack-light/LightPremium.tsx"),
  "./components/mockups/glev-logos/GlevLogos.tsx": () => import("../components/mockups/glev-logos/GlevLogos.tsx")
};
