// Shared types & constants for the Dev Cockpit (Phase 2 — persistence).
//
// Imported by both the server side (page.tsx, actions.ts) and the client
// component (DevCockpit.tsx). Keep this file free of "use server" / "use
// client" directives and of any Node-only imports so it can be pulled into
// either environment.

// ── Task ──────────────────────────────────────────────────────────────────

export type TaskStatus =
  | "draft"
  | "planning"
  | "waiting_for_start"
  | "waiting_for_input"
  // ── Phase 5 — Build Execution lifecycle ──
  | "planning_build" // Start Build clicked, build plan being generated
  | "build_ready" // build plan generated, ready (Phase 6 will execute)
  | "building"
  | "build_failed"
  | "build_complete"
  | "preview_ready"
  | "applied"
  | "rejected"
  | "cancelled"
  | "archived"
  | "backlog";

export interface DevTask {
  id: string;
  title: string;
  prompt: string | null;
  status: TaskStatus;
  branch_name: string | null;
  preview_url: string | null;
  plan_text: string | null;
  // Phase 5 — generated build-execution plan (BuildExecutionPlan JSON) or null.
  build_plan: unknown | null;
  diff_summary: string | null;
  changed_files: unknown[];
  created_at: string;
  updated_at: string;
}

// ── Message ───────────────────────────────────────────────────────────────

export type MessageRole = "user" | "assistant" | "system";

export interface DevMessage {
  id: string;
  task_id: string;
  role: MessageRole;
  content: string;
  created_at: string;
}

// ── Attachment (metadata only in Phase 2) ──────────────────────────────────

export interface DevAttachment {
  id: string;
  task_id: string;
  file_name: string;
  file_type: string | null;
  file_url_or_storage_path: string | null;
  created_at: string;
}

// ── Prompt Queue ───────────────────────────────────────────────────────────

export type QueueStatus =
  | "queued"
  | "evaluated"
  | "applied"
  | "after_build_pending" // Phase 4: queued for a later follow-up build
  | "discarded"
  | "converted_to_task";

export type ImpactLevel = "low" | "medium" | "high";

export type Recommendation =
  | "current_build"
  | "after_build"
  | "separate_task"
  | "discard";

export interface DevQueueNote {
  id: string;
  task_id: string;
  content: string;
  status: QueueStatus;
  impact_level: ImpactLevel | null;
  recommendation: Recommendation | null;
  evaluation_text: string | null;
  // Phase 4 — structured evaluation extras + apply marker.
  affected_areas: unknown[];
  risks: unknown[];
  approved_for_current_build: boolean;
  created_at: string;
  updated_at: string;
}

/** Structured Mistral evaluation of a single queue note (Phase 4). */
export interface QueueEvaluation {
  impact_level: ImpactLevel;
  recommendation: Recommendation;
  evaluation_text: string;
  affected_areas: string[];
  risks: string[];
}

// Column list used by every queue-note SELECT so the shape always matches DevQueueNote.
export const QUEUE_COLUMNS =
  "id, task_id, content, status, impact_level, recommendation, evaluation_text, affected_areas, risks, approved_for_current_build, created_at, updated_at";

// ── Analysis Plan (Phase 3 — Mistral analysis result) ───────────────────────

/**
 * Structured output of `analyzeTask()`. Mistral returns exactly this shape as
 * JSON; it is stored (stringified) in `dev_cockpit_tasks.plan_text` and
 * rendered as the "Analyse-Plan" card (never shown as raw JSON).
 */
export interface BuildPlan {
  summary: string;
  affected_areas: string[];
  likely_files: string[];
  /**
   * Plausible assumptions the architect made to keep planning instead of
   * blocking. Normal uncertainties (unknown exact file, SQL-vs-TS, minor
   * design details, …) land here — NOT in `questions` — so `ready_to_build`
   * can stay true.
   */
  assumptions: string[];
  risks: string[];
  /** Only REAL blockers (see system prompt). Empty unless a user answer is truly required. */
  questions: string[];
  ready_to_build: boolean;
}

// ── Build Execution Plan (Phase 5) ──────────────────────────────────────────

export type Complexity = "low" | "medium" | "high";

/**
 * Generated by "Start Build" (Phase 5). Plan only — NO code generation yet
 * (that's Phase 6). Stored as JSON in `dev_cockpit_tasks.build_plan` and
 * rendered as the "Build Plan" card.
 *
 * included_notes = current-build queue notes (status applied +
 * approved_for_current_build). excluded_notes = after_build_pending notes,
 * shown explicitly as deferred. separate_task notes are ignored entirely.
 */
export interface BuildExecutionPlan {
  scope: string;
  steps: string[];
  included_notes: string[];
  excluded_notes: string[];
  affected_areas: string[];
  risks: string[];
  complexity: Complexity;
}

// ── Sidebar filters ─────────────────────────────────────────────────────────

export type TaskFilter =
  | "active"
  | "backlog"
  | "archived"
  | "cancelled"
  | "applied"
  | "rejected"
  | "all";

/**
 * "Active" = the in-flight working set shown by default in the sidebar.
 * Everything else (cancelled / archived / backlog / applied / rejected) is
 * reachable via the filter chips.
 */
export const ACTIVE_STATUSES: TaskStatus[] = [
  "draft",
  "planning",
  "waiting_for_start",
  "waiting_for_input",
  "planning_build",
  "build_ready",
  "building",
  "build_failed",
  "build_complete",
  "preview_ready",
];

/** Which DB statuses each sidebar filter resolves to (null = no status filter). */
export const FILTER_STATUSES: Record<TaskFilter, TaskStatus[] | null> = {
  active: ACTIVE_STATUSES,
  backlog: ["backlog"],
  archived: ["archived"],
  cancelled: ["cancelled"],
  applied: ["applied"],
  rejected: ["rejected"],
  all: null,
};

export const FILTER_LABEL: Record<TaskFilter, string> = {
  active: "Active",
  backlog: "Backlog",
  archived: "Archived",
  cancelled: "Cancelled",
  applied: "Applied",
  rejected: "Rejected",
  all: "All",
};

export const FILTER_ORDER: TaskFilter[] = [
  "active",
  "backlog",
  "archived",
  "cancelled",
  "applied",
  "rejected",
  "all",
];

// ── Status display ──────────────────────────────────────────────────────────

export const STATUS_LABEL: Record<TaskStatus, string> = {
  draft: "Entwurf",
  planning: "Planung",
  waiting_for_start: "Wartet auf Start",
  waiting_for_input: "Wartet auf Input",
  planning_build: "Build-Planung",
  build_ready: "Build bereit",
  building: "Building",
  build_failed: "Build fehlgeschlagen",
  build_complete: "Build fertig",
  preview_ready: "Preview bereit",
  applied: "Angewendet",
  rejected: "Abgelehnt",
  cancelled: "Abgebrochen",
  archived: "Archiviert",
  backlog: "Backlog",
};

export const STATUS_STYLE: Record<TaskStatus, React.CSSProperties> = {
  draft: { background: "#f3f4f6", color: "#374151", border: "1px solid #d1d5db" },
  planning: { background: "#dbeafe", color: "#1e40af", border: "1px solid #93c5fd" },
  waiting_for_start: { background: "#fef9c3", color: "#854d0e", border: "1px solid #fde047" },
  waiting_for_input: { background: "#fef3c7", color: "#92400e", border: "1px solid #fcd34d" },
  planning_build: { background: "#e0e7ff", color: "#3730a3", border: "1px solid #a5b4fc" },
  build_ready: { background: "#dcfce7", color: "#166534", border: "1px solid #86efac" },
  building: { background: "#ffedd5", color: "#9a3412", border: "1px solid #fed7aa" },
  build_failed: { background: "#fee2e2", color: "#991b1b", border: "1px solid #fca5a5" },
  build_complete: { background: "#d1fae5", color: "#065f46", border: "1px solid #6ee7b7" },
  preview_ready: { background: "#f3e8ff", color: "#6b21a8", border: "1px solid #d8b4fe" },
  applied: { background: "#dcfce7", color: "#166534", border: "1px solid #86efac" },
  rejected: { background: "#fee2e2", color: "#991b1b", border: "1px solid #fca5a5" },
  cancelled: { background: "#f3f4f6", color: "#6b7280", border: "1px solid #d1d5db" },
  archived: { background: "#e5e7eb", color: "#4b5563", border: "1px solid #cbd5e1" },
  backlog: { background: "#fef3c7", color: "#92400e", border: "1px solid #fcd34d" },
};

// Column list used by every task SELECT so the shape always matches DevTask.
export const TASK_COLUMNS =
  "id, title, prompt, status, branch_name, preview_url, plan_text, build_plan, diff_summary, changed_files, created_at, updated_at";
