-- Superseded by 20260425_add_insulin_exercise_logs.sql.
-- Schema reshape: insulin_logs columns changed (insulin_type, insulin_name,
-- cgm_glucose_at_log, notes) and exercise_logs added in the same migration.
-- Intentionally empty so re-running this folder is a no-op.
